# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='img',
            field=models.URLField(default='http://g.com/', verbose_name='Image URL'),
        ),
    ]
