# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20160621_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='slug',
        ),
    ]
